dataset:  ./data/train/acm_ccs_clean.csv # ./data/bansal_wordnet_true_pairs.csv
prompt_learning: False
learnable_layers: 0
check_val_every_n_epoch: 1
negative_ratio: 3
lr: 0.0001
max_epochs: 25
model_name: lora
batch_size: 64
lora: True
run_dir: /root/autodl-tmp/runs/ccs
logger: wandb