dataset: ./data/acm_ccs_clean.csv # ./data/bansal_wordnet_true_pairs.csv
prompt_learning: False
learnable_layers: 3
check_val_every_n_epoch: 1
negative_ratio: 5
lr: 0.0001
max_epochs: 25
model_name: finetune
batch_size: 64
lora: False
run_dir: /root/autodl-tmp/runs/ccs
logger: wandb